# Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [1]:
import numpy as np
x = np.array([3, 5])
y = np.array([2, 5])
print("Original numbers:")
print(x)
print(y)
print("Comparison - greater")
print(np.greater(x, y))
print("Comparison - greater_equal")
print(np.greater_equal(x, y))
print("Comparison - less")
print(np.less(x, y))
print("Comparison - less_equal")
print(np.less_equal(x, y))

Original numbers:
[3 5]
[2 5]
Comparison - greater
[ True False]
Comparison - greater_equal
[ True  True]
Comparison - less
[False False]
Comparison - less_equal
[False  True]


# Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [4]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)
array=np.ones(10)
print("An array of 10 ones:")
print(array)
#array=np.ones(10)*5
array = np.full([10],5)
print("An array of 10 fives:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5 5 5 5 5 5 5 5 5 5]


# Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array

In [5]:
import numpy as np
x=np.ones([3,3])

print("Sum of all elements:")
print(np.sum(x))
print("Sum of each column:")
print(np.sum(x, axis=0))
print("Sum of each row:")
print(np.sum(x, axis=1))

Sum of all elements:
9.0
Sum of each column:
[3. 3. 3.]
Sum of each row:
[3. 3. 3.]


# Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

In [6]:
import numpy as np
print("Add:")
print(np.add(1.0, 4.0))
print("Subtract:")
print(np.subtract(1.0, 4.0))
print("Multiply:")
print(np.multiply(1.0, 4.0))
print("Divide:")
print(np.divide(1.0, 4.0))

Add:
5.0
Subtract:
-3.0
Multiply:
4.0
Divide:
0.25


# Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in degree.

In [9]:
import numpy as np
y = np.array((30., 45.))
print("sine: array of angles given in degrees")
print(np.sin(y * np.pi / 180.))
print("cosine: array of angles given in degrees")
print(np.cos(y * np.pi / 180.))
print("tangent: array of angles given in degrees")
print(np.tan(y * np.pi / 180.))

sine: array of angles given in degrees
[0.5        0.70710678]
cosine: array of angles given in degrees
[0.8660254  0.70710678]
tangent: array of angles given in degrees
[0.57735027 1.        ]


# Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels

In [10]:
import pandas as pd
import numpy as np

exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


# Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.

In [12]:

print("Select specific columns:")
print(df[['name', 'score']])

Select specific columns:
        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0


# Write a Pandas program to join the two given dataframes along rows and assign all data.

In [13]:
df2 = pd.DataFrame(exam_data , index=labels)
print("Original DataFrames:")
print(df)
print("-------------------------------------")
print(df2)
print("\nJoin the said two dataframes along rows:")
result_data = pd.concat([df, df2])
print(result_data)

Original DataFrames:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
-------------------------------------
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

Join the said two dataframes along rows:
        name  score  attempts qualify
a  Anastasia   12.5      

# Write a Pandas program to detect missing values of a given DataFrame. Display True or False.

In [14]:
print(df.isna())

    name  score  attempts  qualify
a  False  False     False    False
b  False  False     False    False
c  False  False     False    False
d  False   True     False    False
e  False  False     False    False
f  False  False     False    False
g  False  False     False    False
h  False   True     False    False
i  False  False     False    False
j  False  False     False    False


# Write a Pandas program to create and display a one-dimensional array-like object containing an array of data.

In [15]:
ds = pd.Series([2, 4, 6, 8, 10])
print(ds)

0     2
1     4
2     6
3     8
4    10
dtype: int64
